# Generated by Django 2.2.24 on 2021-08-10 11:10

import computedfields.resolver
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('number_of_model_a_objects', models.IntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('model_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcfapp.ModelA')),
            ],
        ),
    ]
